chiters/urls.py
from django.urls import path

from . import views

app_name = 'chiters'
urlpatterns = [
	path('', views.chiters, name='chiters'),
	path('register/', views.register, name='register'),
	path('message/', views.message, name='message'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
	path('', views.index, name='index'),
	path('contact/', views.contact, name='contact'),
	path('about/', views.about, name='about'),
	path('works/', views.works, name='works'),
]

mysite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from rest_framework.schemas import get_schema_view
from rest_framework_swagger.renderers import SwaggerUIRenderer, OpenAPIRenderer
from chiters.views import ChitersList, ChitersDetail
from news.views import NewsList, NewsDetail


schema_view = get_schema_view(
    title='Chitcom API', renderer_classes=[OpenAPIRenderer, SwaggerUIRenderer]
)

urlpatterns = [
    path('', include('home.urls')),
    path('docs/', schema_view, name='docs'),
    path('news/', include('news.urls')),
	path('paperchit/', include('paperchit.urls')),
    path('chiters/', include('chiters.urls')),
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]


api_urlpatterns = [
    path('api/chiters/', ChitersList.as_view(), name='chiters_list'),
    path('api/chiters/<int:pk>/', ChitersDetail.as_view(), name='chiters_detail'),
    path('api/news/', NewsList.as_view(), name='news'),
    path('api/news/<int:pk>', NewsDetail.as_view(), name='news-detail'),
]

urlpatterns += api_urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import (
	PostListView,
	PostDetailView,
	PostCreateView,
	PostUpdateView,
	PostDeleteView,
	UserPostListView
)

app_name = 'news'
urlpatterns = [
	path('', PostListView.as_view(), name='index'),
	path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
	path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
	path('post/new/', PostCreateView.as_view(), name='post-create'),
	path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
	path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paperchit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import (
	ArticleListView,
	ArticleDetailView,
	ArticleCreateView
)


app_name = 'paperchit'
urlpatterns = [
	path('', ArticleListView.as_view(), name='index'),
	path('article/<int:pk>/', ArticleDetailView.as_view(), name='article-detail'),
	path('article/new/', ArticleCreateView.as_view(), name='article-create')
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/views.py
from django.shortcuts import render

def index(request):
	return render(request, 'home/index.html')

def contact(request):
	return render(request, 'home/contact.html')

def about(request):
	return render(request, 'home/about.html')

def works(request):
	return render(request, 'home/works.html')

home/templates/home/about.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}

<h1>О нас</h1>
<p>Chechen IT Community - сообщество по развитию IT-сферы по Чеченской Республике</p>
{% endblock %}

home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>CHITCOM</title>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <!-- Custom styles for this template -->
  <link href="{% static 'home/css/small-business.css' %}" rel="stylesheet">
</head>

<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home:index' %}">CHITCOM</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'news:index' %}">Новости
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'paperchit:index' %}">Статьи</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'chiters:chiters' %}">Читеры</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:about' %}">О нас</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:contact' %}">Контакты</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'profile' %}">Профиль</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Войти</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'register' %}">Регистрация</a>
          </li>
        {% endif %}
        </ul>
      </div>
    </div>
  </nav>  
  <br>

  <div class="container">
    <div class="row">
      <div class="col">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      {% block content %}
      {% endblock %}
      <br>
      </div>
    </div>
  </div>

  <!-- Footer -->
  <footer class="text-light">
      <div class="container">
          <div class="row">
              <div class="col-md-3 col-lg-4 col-xl-3">
                  <h5>О нас</h5>
                  <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
                  <p class="mb-0">
                      Chechen IT Community - сообщество по развитию IT-сферы по Чеченской Республике
                  </p>
              </div>

              <div class="col-md-3 col-lg-2 col-xl-2 mx-auto">
                  <h5>Ссылки</h5>
                  <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
                  <ul class="list-unstyled">
                      <li><a href="{% url 'home:index' %}">Главная страница</a></li>
                      <li><a href="{% url 'news:index' %}">Новости</a></li>
                      <li><a href="{% url 'chiters:chiters' %}">Читеры</a></li>
                      <li><a href="{% url 'home:about' %}">О нас</a></li>
                      <li><a href="{% url 'home:contact' %}">Контакты</a></li>
                  </ul>
              </div>

              <div class="col-md-4 col-lg-3 col-xl-3">
                  <h5>Контакты</h5>
                  <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
                  <ul class="list-unstyled">
                      <li>CHITCOM</li>
                      <li>Чеченская Республика</li>
                      <li>chitcomhub@mail.ru</li>
                  </ul>
              </div>
              <div class="col-12 copyright mt-3">
                  <p class="float-left">
                      <a href="#">Вверх</a>
                  </p>
              </div>
              <div class="container">
                <p class="m-0 text-center text-white">Copyright &copy; CHITCOM 2018</p>
              </div>
          </div>
      </div>
  </footer>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>

home/templates/home/contact.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'home:index' %}">Главная</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Контакты</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header bg-primary text-white"><i class="fa fa-envelope"></i> Форма отправки временно недоступна<!-- Наши контакты -->
                </div>
                <div class="card-body">
                    <form>
                        <div class="form-group">
                            <label for="name">Имя</label>
                            <input type="text" class="form-control" id="name" aria-describedby="emailHelp" placeholder="Введите имя" required>
                        </div>
                        <div class="form-group">
                            <label for="email">Email адрес</label>
                            <input type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Введите email" required>
                            <small id="emailHelp" class="form-text text-muted">Ваша почта будет скрыта от посторонних</small>
                        </div>
                        <div class="form-group">
                            <label for="message">Сообщение</label>
                            <textarea class="form-control" id="message" rows="6" required></textarea>
                        </div>
                        <div class="mx-auto">
                        <button type="submit" class="btn btn-primary text-right">Отправить</button></div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-4">
            <div class="card bg-light mb-3">
                <div class="card-header bg-success text-white text-uppercase"><i class="fa fa-home"></i>Адрес</div>
                <div class="card-body">
                    <p>CHITCOM</p>
                    <p>Чеченская Республика</p>
                    <p>Почта: chitcomhub@mail.ru</p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}

<!-- Page Content -->
<div class="container">

  <!-- Heading Row -->
  <div class="row my-4">
    <div class="col-lg-8">
      <img class="img-fluid rounded" src="{% static 'home/images/banner.png' %}" alt="">
    </div>
    <!-- /.col-lg-8 -->
    <div class="col-lg-4">
      <h1>Chechen IT Community</h1>
      <p>Площадка для IT-специалистов Чеченской Республики. Давайте вместе развивать IT-сферу нашей Республики. Вступайте в наше сообщество.</p>
      <a class="btn btn-primary btn-lg" href="{% url 'chiters:register' %}">Вступить</a>
    </div>
    <!-- /.col-md-4 -->
  </div>
  <!-- /.row -->

  <!-- Call to Action Well -->
  <div class="card text-white bg-secondary my-4 text-center">
    <div class="card-body">
      <p class="text-white m-0">Сайт находится на стадии разработки! Последнее обновление сайта было в 19:00 23.11.2018</p>
    </div>
  </div>

  <!-- Content Row -->
  <div class="row">
    <div class="col-md-4 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <h2 class="card-title">Веб-приложения</h2>
          <p class="card-text">Здесь собраны материалы по веб-разработке</p>
        </div>
        <div class="card-footer">
          <a href="#" class="btn btn-primary">Подробнее</a>
        </div>
      </div>
    </div>
    <!-- /.col-md-4 -->
    <div class="col-md-4 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <h2 class="card-title">Мобильные приложения</h2>
          <p class="card-text">Здесь собраны материалы по разработке мобильных приложений</p>
        </div>
        <div class="card-footer">
          <a href="#" class="btn btn-primary">Подробнее</a>
        </div>
      </div>
    </div>
    <!-- /.col-md-4 -->
    <div class="col-md-4 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <h2 class="card-title">Нейронные сети</h2>
          <p class="card-text">Здесь собраны материалы по нейронным сетям</p>
        </div>
        <div class="card-footer">
          <a href="#" class="btn btn-primary">Подробнее</a>
        </div>
      </div>
    </div>
    <!-- /.col-md-4 -->
  </div>
  <!-- /.row -->

</div>
<!-- /.container -->

{% endblock %}

home/templates/home/works.html
{% load static %}
<!doctype html>
<html> 
<head> 
	<meta charset="utf-8" />
	<title>CHITCOM</title>
	<link href="{% static 'home/css/style.css' %}" rel="stylesheet"/>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'home/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'home/css/small-business.css' %}" rel="stylesheet">
</head>

<body>
	<div id="level">
		<div id="content">
			<div id="gears">
				<div id="gears-static"></div>
				<div id="gear-system-1">
					<div id="gear15"></div>
					<div id="gear14"></div>
					<div id="gear13"></div>
				</div>
				<div id="gear-system-2">
					<div id="gear10"></div>
					<div id="gear3"></div>
				</div>
				<div id="gear-system-3">
					<div id="gear9"></div>
					<div id="gear7"></div>
				</div>
				<div id="gear-system-4">
					<div id="gear6"></div>
					<div id="gear4"></div>
				</div>
				<div id="gear-system-5">
					<div id="gear12"></div>
					<div id="gear11"></div>
					<div id="gear8"></div>
				</div>
				<div id="gear1"></div>
				<div id="gear-system-6">
					<div id="gear5"></div>
					<div id="gear2"></div>
				</div>
				<div id="chain-circle"></div>
				<div id="chain"></div>
				<div id="weight"></div>
			</div>
			<div id="title">
				<h1>Добро пожаловать на сайт Chechen IT Community</h1>
				<p>На данный момент сайт находится на стадии разработки</p>
				<p><a href="{% url 'home:index' %}">Вернуться на сайт</a></p>
			</div>
		</div>
	</div>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'home/jquery/jquery.min.js' %}"></script>
<script src="{% static 'home/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>