home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
	path('', views.index, name='index'),
	path('contact/', views.contact, name='contact'),
	path('about/', views.about, name='about'),
	path('works/', views.works, name='works'),
]

mysite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from rest_framework.schemas import get_schema_view
from rest_framework_swagger.renderers import SwaggerUIRenderer, OpenAPIRenderer
from chiters.views import ChitersList, ChitersDetail
from news.views import NewsList, NewsDetail


schema_view = get_schema_view(
    title='Chitcom API', renderer_classes=[OpenAPIRenderer, SwaggerUIRenderer]
)

urlpatterns = [
    path('', include('home.urls')),
    path('docs/', schema_view, name='docs'),
    path('news/', include('news.urls')),
	path('paperchit/', include('paperchit.urls')),
    path('chiters/', include('chiters.urls')),
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]


api_urlpatterns = [
    path('api/chiters/', ChitersList.as_view(), name='chiters_list'),
    path('api/chiters/<int:pk>/', ChitersDetail.as_view(), name='chiters_detail'),
    path('api/news/', NewsList.as_view(), name='news'),
    path('api/news/<int:pk>', NewsDetail.as_view(), name='news-detail'),
]

urlpatterns += api_urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import (
	PostListView,
	PostDetailView,
	PostCreateView,
	PostUpdateView,
	PostDeleteView,
	UserPostListView
)

app_name = 'news'
urlpatterns = [
	path('', PostListView.as_view(), name='index'),
	path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
	path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
	path('post/new/', PostCreateView.as_view(), name='post-create'),
	path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
	path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class Post(models.Model):
	title = models.CharField('Заголовок', max_length=200)
	content = models.TextField('Описание')
	datetime = models.DateTimeField('Дата публикации', default=timezone.now)
	pic = models.ImageField(null=True, blank=True, upload_to='images/', verbose_name='Изображение', help_text='Ширина и высота 800x400px')
	author = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('news:post-detail', kwargs={'pk': self.pk})

news/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import (
	ListView,
	DetailView,
	CreateView,
	UpdateView,
	DeleteView
)
from .models import Post
from .serializers import PostSerializer
from rest_framework import generics

class PostListView(ListView):
	model = Post
	template_name = 'news/index.html'
	context_object_name = 'posts'
	ordering = ['-datetime']
	paginate_by = 5


class UserPostListView(ListView):
	model = Post
	template_name = 'news/user_posts.html'
	context_object_name = 'posts'
	paginate_by = 5

	def get_queryset(self):
		user = get_object_or_404(User, username = self.kwargs.get('username'))
		return Post.objects.filter(author=user).order_by('-datetime')


# Здесь был Азамат
class PostDetailView(DetailView):
	model = Post


class PostCreateView(LoginRequiredMixin, CreateView):
	model = Post
	fields = ['title', 'content']

	def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = Post
	fields = ['title', 'content']

	def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)

	def test_func(self):
		post = self.get_object()
		if self.request.user == post.author:
			return True
		return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = Post
	success_url = '/news'

	def test_func(self):
		post = self.get_object()
		if self.request.user == post.author:
			return True
		return False



#API Views
class NewsList(generics.ListCreateAPIView):
	queryset = Post.objects.all()
	serializer_class = PostSerializer


	def perform_create(self, serializer):
		serializer.save(author=self.request.user)


class NewsDetail(generics.RetrieveUpdateDestroyAPIView):
	queryset = Post.objects.all()
	serializer_class = PostSerializer

news/templates/news/index.html
{% extends 'home/base.html' %}

{% block content %}
	<nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home:index' %}">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page">Новости</li>
        </ol>
    </nav>

    <div class="container">
    	<div class="row justify-content-md-center">
    		<div class="col-md-8">
    			{% if user.is_authenticated %}
    			<div>
	              <a class="btn btn-primary btn-sm mt-1 mb-1" href="{% url 'news:post-create' %}">Написать новость</a>
	            </div>
	            {% endif %}
    			{% for post in posts %}
				<div class="card-deck">
				  <div class="card">
				  	{% if post.pic %}
				    <a href="{% url 'news:post-detail' post.id %}"><img class="card-img-top" src="/news{{ post.pic.url }}" alt="Card image cap"></a>
				    {% endif %}
				    <div class="card-body">
				      <h5 class="card-title"><a href="{% url 'news:post-detail' post.id %}">{{ post.title }}</a></h5>
				      <p class="card-text">{{ post.content }}</p>
				    </div>
				    <div class="card-footer">
			    	  	<div class="article-metadata">
			    	  		<img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
							<a class="mr-2" href="{% url 'news:user-posts' post.author.username %}">{{ post.author }}</a>
							<small class="text-muted">{{ post.datetime|date:"F d, Y" }}</small>
						</div>
				    </div>
				  </div>
				</div>
				<br>
				{% endfor %}

				{% if is_paginated %}

					{% if page_obj.has_previous %}
						<a class="btn btn-outline-info mb-4" href="?page=1">Первый</a>
						<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Предыдущий</a>
					{% endif %}

					{% for num in page_obj.paginator.page_range %}
						{% if page_obj.number == num %}
							<a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
						{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
							<a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
						{% endif %}
					{% endfor %}

					{% if page_obj.has_next %}
						<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Следующий</a>
						<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Последний</a>
					{% endif %}

				{% endif %}
    		</div>
    	</div>
    </div>
{% endblock %}	

news/templates/news/post_confirm_delete.html
{% extends "home/base.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Удалить пост</legend>
				<h2>Вы уверены, что хотите удалить пост "{{ object.title }}"?</h2>
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-danger" type="submit">Удалить</button>
				<a class="btn btn-outline-secondary" href="{% url 'news:post-detail' object.id %}">Отмена</a>
			</div>
		</form>
	</div>
{% endblock content %} 

news/templates/news/post_detail.html
{% extends 'home/base.html' %}

{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home:index' %}">Главная</a></li>
        <li class="breadcrumb-item"><a href="{% url 'news:index' %}">Новости</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ object.title }}</li>
    </ol>
</nav>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-md-10"">
      <div class="card mb-3">
        {% if object.pic %}
        <img class="card-img-top" src="/news{{ object.pic.url }}" alt="Card image cap">
        {% endif %}
        <div class="card-body">
          {% if object.author == user %}
            <div>
              <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'news:post-update' object.id %}">Обновить</a>
              <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'news:post-delete' object.id %}">Удалить</a>
            </div>
          {% endif %}
          <h5 class="card-title">{{ object.title }}</h5>
          <p class="card-text">{{ object.content }}</p>
          <div class="card-footer">
            <div class="article-metadata">
              <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
              <a class="mr-2" href="{% url 'news:user-posts' object.author.username %}">{{ object.author }}</a>
              <small class="text-muted">{{ object.datetime|date:"F d, Y" }}</small>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

news/templates/news/post_form.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Новостной пост</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Запостить</button>
			</div>
		</form>
	</div>
{% endblock content %}

news/templates/news/user_posts.html
{% extends "home/base.html" %}
{% block content %}
	<div class="container">
    	<div class="row justify-content-md-center">
    		<div class="col-md-8">
			<h1 class="mb-3">Посты от автора: {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
			{% for post in posts %}
				<div class="card-deck">
				  <div class="card">
				  	{% if post.pic %}
				    <a href="{% url 'news:post-detail' post.id %}"><img class="card-img-top" src="/news{{ post.pic.url }}" alt="Card image cap"></a>
				    {% endif %}
				    <div class="card-body">
				      <h5 class="card-title"><a href="{% url 'news:post-detail' post.id %}">{{ post.title }}</a></h5>
				      <p class="card-text">{{ post.content }}</p>
				    </div>
				    <div class="card-footer">
			    	  	<div class="article-metadata">
			    	  		<img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
							<a class="mr-2" href="{% url 'news:user-posts' post.author.username %}">{{ post.author }}</a>
							<small class="text-muted">{{ post.datetime|date:"F d, Y" }}</small>
						</div>
				    </div>
				  </div>
				</div>
				<br>
			{% endfor %}
			<br>
			{% if is_paginated %}

				{% if page_obj.has_previous %}
					<a class="btn btn-outline-info mb-4" href="?page=1">Первый</a>
					<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Предыдущий</a>
				{% endif %}

				{% for num in page_obj.paginator.page_range %}
					{% if page_obj.number == num %}
						<a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
					{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
						<a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
					{% endif %}
				{% endfor %}

				{% if page_obj.has_next %}
					<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Следующий</a>
					<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Последний</a>
				{% endif %}

			{% endif %}
			</div>
		</div>
	</div>
{% endblock %}